services:
  frontend:
    build:
      context: ./client
    image: "node-frontend"
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    networks:
      - react-express2
    depends_on:
      - backend
  backend:
    restart: always
    build: .
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - express-mongo2
      - react-express2
    expose: 
      - 5000
  mongodb:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo2
    expose:
      - 27017
networks:
  react-express2:
  express-mongo2:
