version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "node-backend"
    links:
      - database
    depends_on:
      - database
    ports:
      - "5005:5000"
    networks: 
     - network-backend
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "node-frontend"
    depends_on:
      - backend
    ports:
      - "3003:3000"
    networks: 
     - network-backend
  database:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_test
    # uncomment following lines to access db locally
    ports:
      - 27017:27017
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data: